#dev分支配置文件
server:
  port: 8081
spring:
  application:
    name: dzdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.227.164:3306/dzdp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  redis:
    host: 47.113.227.164
    port: 6379
    password: root123
    database: 1
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 0
        max-wait: 5s
        time-between-eviction-runs: 1s

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dzdp.entity # 别名扫描包
logging:
  level:
    com.dzdp: debug